// <auto-generated />
using InvestView.Infrastructure.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace InvestView.Infrastructure.Data.Migrations
{
    [DbContext(typeof(InvestViewDbContext))]
    [Migration("20260714103000_AddHoldingPendingReceiveQuantity")]
    partial class AddHoldingPendingReceiveQuantity
    {
    }
}
